export const SERVICE_NAME = "TECH TALK"
export const NOTION_ARTICLE_QUERY_PAGE_SIZE = 100
export const INITIAL_PAGE_ARTICLE_SIZE = 8
export const ARTICLE_LIST_PAGE_ARTICLE_SIZE = 8
export const REVALIDATE_INTERVAL = 60 * 60
